### ISSUE TITLE
Cant place basic Redstone components (Observer, pistons, slime etc.)

### ISSUE THREAD

**Issue by PastaPad** [MCHPR/MCHPRS#102]
I started MCHPRS through ubuntu server and i cant place observers pistons and other components. Is there any way to modify it ?

**Comment by rtyyyyb** [comment]
nope as those blocks aren't MCHPRS compatible so it just wont let you place them

**Comment by commanderguy3001** [comment]
there are only very few things that are actually supported in mchprs, that being basic redstone, buttons, trapdoors for displays, and that's basically it.
Why?
To keep it as small and light weight as possible, which allows it to be a lot faster, which is the main goal of mchprs.

**Comment by Olek47** [comment]
IDEA: Send info on a chat when someone is trying to use pistons or observers

**Comment by SuperBasher90** [comment]
please add support for other Redstone components I need them for my Redstone computer.

**Comment by LordDecapo** [comment]
Adding piston support would take the current TPS that people are getting...
and drop it like crazy. Anything that manipulates block placement is very
difficult to get going with the way MCHPRS acceleration works.
