### ISSUE TITLE
Compile error `regex` in Ubuntu Linux

### ISSUE THREAD

**Issue by BGOPC** [MCHPR/MCHPRS#110]
After I cloned the project On my Linux machine and tried to compile it I get this error:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /home/bgopc/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.8.1/src/lib.rs:644:42
    |
644 | #![cfg_attr(feature = "pattern", feature(pattern))]
    |                                          ^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `regex` due to previous error
```

I reCloned the project a few times but nothing seemed to fix it, I have rust programming experience and I'm on my main linux Machine
rustc version: `1.65.0`
cargo version: `1.65.0`

**Comment by EwanFox** [comment]
Can you try running the following command before building:
`rustup override set nightly`
and if that doesn't fix anything, you can try:
`cargo clean`

**Comment by BGOPC** [comment]
So I tried reInstalling my rust and it worked, turns out it was a problem of apt rust package
