### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by gabriel-doriath-dohler** [MCHPR/MCHPRS#113]
Could you please create a new release?

The latest release contains security concerns (eg. #65) and doesn't support 1.18.2.
I'm packaging MCHPRS in [nixpkgs](https://github.com/NixOS/nixpkgs), which would enable easy deployment for Nix users. Creating a new release would help to get this packaging effort accepted upstream.

**Comment by StackDoubleFlow** [comment]
Just released [v0.4](https://github.com/MCHPR/MCHPRS/releases/tag/v0.4)
