### ISSUE TITLE
Wrong version in `Cargo.toml`

### ISSUE THREAD

**Issue by gabriel-doriath-dohler** [MCHPR/MCHPRS#114]
v0.4 is tagged but `Cargo.toml` still indicates 0.3:
https://github.com/MCHPR/MCHPRS/blob/fec9b7098595fcec172c533cad1e4ad557b75568/Cargo.toml#L6C12-L6C17

**Comment by StackDoubleFlow** [comment]
oop good point haha

**Comment by StackDoubleFlow** [comment]
Released v0.4.1 with the correct version number set.
