### ISSUE TITLE
builds bigger than 256x256?

### ISSUE THREAD

**Issue by solstacoded** [MCHPR/MCHPRS#126]
i've been making a cpu that i wanna try running on this, but it's a bit big (~270x400, it's not very space efficient and has a LOT of rom).

is the server capable of running redstone over multiple plots or will i just have to fork the code and figure out how to change the plot size?

**Comment by commanderguy3001** [comment]
you don't have to fork the code to figure out how to change it. overall, it should be easy to change:
`./crates/core/src/plot/mod.rs, line 43`
that is the size of the plot in chunks in powers of two, e.g. if you want 512x512 blocks, that is 32x32 chunks, e.g. set that line to `5`.

**Comment by AL1L** [comment]
If you dont/cant do what @commanderguy3001 suggested, could also try to take better advantage of vertical space.

**Comment by solstacoded** [comment]
forgot to comment earlier, i was able to get it to work with 512x512 plots. thanks for pointing that out to me. can i just ask is there a particular reason it only does powers of two?

**Comment by commanderguy3001** [comment]
nice.
I don't know exactly why it's gotta be powers of two for the chunks, but I'll bet "technical reasons in terms of memory management/something like that"

**Comment by StackDoubleFlow** [comment]
It's too make sure converting block to plot coordinates is as simple as a bit shift or finding the offset of a block in a plot is as simple as bit masking.
