### ISSUE TITLE
instant repeater block

### ISSUE THREAD

**Issue by clementtttttttt** [MCHPR/MCHPRS#141]
can't make them in this due to the lack of pistons, tried to add one myself but was unable to do so

**Comment by AL1L** [comment]
Dupe of #102 

Also, idk too much about the current state of redpiler, but I believe introducing pistons would be rather difficult with it.

**Comment by clementtttttttt** [comment]
this issue is about introducing an entirely new block that repeats the signal instantly though

**Comment by AL1L** [comment]
Probably should make that more clear in the initial post. Also ideally the builds in MCHPRS should be compatible with Vanilla Minecraft, so creating a new block (or more accurately using another block for this purpose) would break that inter-compatibility.

**Comment by clementtttttttt** [comment]
would it be possible to just use one of the unsupported blocks to implement it, e.g. a pumpkin (accidentally closed this issue sorry)
