### ISSUE TITLE
Signs not working

### ISSUE THREAD

**Issue by haylinmoore** [MCHPR/MCHPRS#17]
Signs appear not to be working. When I try to place them they just act like all of the other blocks that have no been added yet. I believe that they are supposed to work as they appear to be implemented in https://github.com/MCHPR/MCHPRS/blob/master/src/blocks/mod.rs#L481-L490 and a couple other lines.

**Comment by StackDoubleFlow** [comment]
At this moment, signs can only be loaded from schematic files.

**Comment by haylinmoore** [comment]
Ah thank you
