### ISSUE TITLE
Tripwire Hooks can be loaded from schematics, but are not placeable.

### ISSUE THREAD

**Issue by StackDoubleFlow** [MCHPR/MCHPRS#21]
A new placeable TripwireHook item should be created. You can find the appropriate item id [here](https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.16.2/items.json).

**Comment by ghost** [comment]
Alr I'll do this one

**Comment by ghost** [comment]
I fixed this and did a pull request (https://github.com/MCHPR/MCHPRS/pull/22)

**Comment by BananaSquares** [comment]
Create pr (#53 )

**Comment by EwanFox** [comment]
@StackDoubleFlow You can close this issue now
