### ISSUE TITLE
Incorrect redstone connection

### ISSUE THREAD

**Issue by Teln0** [MCHPR/MCHPRS#33]
![image](https://user-images.githubusercontent.com/45608575/104232146-33e9a880-5450-11eb-87df-e02b7b5b4cbd.png)

**Comment by Teln0** [comment]
Gets updated and becomes correct when broken and replaced (this comes from a schematic)

**Comment by StackDoubleFlow** [comment]
My guess is it was just saved in the schematic this way. MCHPRS does not do anything to correct these issues, and I'm not too sure we should as updating the blocks may cause unintended behavior. Did it look like that before saving the schematic originally?
