### ISSUE TITLE
Undo/Redo support.

### ISSUE THREAD

**Issue by StackDoubleFlow** [MCHPR/MCHPRS#4]
Making a mistake can be very costly without the `//undo` command.

An idea would be to create a `WorldEditClipboard` of the region before starting the operation, and then paste it there when the player runs `//undo`.

**Comment by haylinmoore** [comment]
Would the player then in effect have two clipboards stored on their player? A main world edit clipboard and then a clipboard of their whole plot everytime thats changed everytime they run a worldedit command?

**Comment by StackDoubleFlow** [comment]
The player would store an array of clipboards for undo. I don’t think it should be of the entire plot but instead just the changed region.

**Comment by StackDoubleFlow** [comment]
Undo support was added back in 705b792c9d63c1a8098eb8978110348cf5ac4fb4. All that's needed now is the `//redo` command.

**Comment by StackDoubleFlow** [comment]
Redo was implemented in 416b6ecb6a08a7972aff7a399d44462766c0a703
