### ISSUE TITLE
piston implementation

### ISSUE THREAD

**Issue by mokurin000** [MCHPR/MCHPRS#48]

**Comment by AL1L** [comment]
Why

**Comment by mokurin000** [comment]
> Why

Pistons are used in some redstone circuits for simplification,
there are also redstone machines that rely on pistons.

**Comment by AL1L** [comment]
Pistons will require a lot of work and probably some refactoring to add them

**Comment by poly000** [comment]
Probably this issue will hang for a long time ...... But it can also be used to track the development process of the piston, although not now
