### ISSUE TITLE
/container barrel <value> does not work.

### ISSUE THREAD

**Issue by KittenMeow** [MCHPR/MCHPRS#52]
Hello! When I write `/container barrel 14`, the server kicks me out. It says "Packet 0/22 (qk) was larger than I expected, found 1217 bytes extra whilst reading packet 22." When I rejoin, the barrel is there, filled with just redstone dust, and it's one signal strength longer than it should be. The server doesn't crash at all, it just appears to be a java error.

Thanks!

**Comment by StackDoubleFlow** [comment]
fixed
