### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by ZephyrysBaum** [MCHPR/MCHPRS#56]
'git' is not recognized as an internal or external command,
operable program or batch file.

**Comment by commanderguy3001** [comment]
could you provide a proper log of all the commands you ran and the output for these commands?
Also: please specify your environment, what OS are you using, and did you install rust and git?

**Comment by EwanFox** [comment]
Yeah the issue is that you don’t have git installed, you can get it here for Windows.
https://git-scm.com/
