### ISSUE TITLE
Worldedit //rotate and //flip commands

### ISSUE THREAD

**Issue by Sjorsm** [MCHPR/MCHPRS#62]

**Comment by StackDoubleFlow** [comment]
What's actually the issue here?

**Comment by Sjorsm** [comment]
No issue. It would just be nice. So I thought I put it here.

**Comment by EwanFox** [comment]
It’s already a thing?

**Comment by StackDoubleFlow** [comment]
Indeed, both //rotate and //flip is already implemented.

**Comment by Sjorsm** [comment]
![2022-02-24_11 22 09](https://user-images.githubusercontent.com/65414886/155506717-d914bdc8-a03f-4088-b864-153692981d6c.png)
Sorry I hadn't tested it. I just saw 'unknown or incomplete command' and assumed that it didn't work.
