### ISSUE TITLE
Teleport to infinity and NaN!

### ISSUE THREAD

**Issue by gabriel-doriath-dohler** [MCHPR/MCHPRS#67]
Coordinates are parsed to IEEE754 floats with Rust's `parse` method, which allows for `infinity`, `-infinity`, `inf`, `-inf`, `nan` and `-nan` (and is not case-sensitive).

This causes some weird behavior such as:

- `//tp inf 10 inf` teleports the player a bit outside the world barrier
- `//tp NaN 10 10` hangs my client (I had to kill my client and delete the player's file to fix it)
- `//tp 0 inf 0` hangs my client (I had to kill my client and delete the player's file to fix it)

**Comment by gabriel-doriath-dohler** [comment]
Relevant documentation on the parsing of floats in Rust:
https://doc.rust-lang.org/std/primitive.f64.html#grammar
with the correction
https://github.com/rust-lang/rust/commit/4c17217f99250892f859d2859aa0f17e949a6ebc

**Comment by AL1L** [comment]
I say keep this as a feature 😉
