### ISSUE TITLE
plot crashes when compiling redpiler.

### ISSUE THREAD

**Issue by elapt1c** [MCHPR/MCHPRS#77]
whenever redpiler runs the plot crashes and sends this error in console:
`[ERROR] plot panicked at 'divide by zero error when dividing duration by scalar', library\core\src\time.rs:979:9` please fix this as its ruening everything

**Comment by StackDoubleFlow** [comment]
Should be fixed in 2ad05d8e33a2ce502c6b26a0e150db28570e60de, could you please try it out?
