### ISSUE TITLE
A player tried to connect using the wrong version

### ISSUE THREAD

**Issue by hohowt** [MCHPR/MCHPRS#90]
client version is 1.18.2
When I log in I am prompted that the version is 1.15.2
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/56286666/196602386-27a8ae04-cb09-4adb-8d80-f34d8c912411.png">

**Comment by hohowt** [comment]
> client version is 1.18.2 When I log in I am prompted that the version is 1.15.2 <img alt="image" width="1313" src="https://user-images.githubusercontent.com/56286666/196602386-27a8ae04-cb09-4adb-8d80-f34d8c912411.png">

MCHPRS's version is Pre-release 0.3

**Comment by StackDoubleFlow** [comment]
Current latest 0.4.1 supports 1.18.2.
